# -*- mode: ruby -*-
# vi: set ft=ruby :

NUM_VM = 7
SUBNET = "192.168.33."

Vagrant.configure("2") do |config|
  NUM_VM.times do |n|
    config.vm.define "cloud#{n+1}", autostart: true do |compute|
      vm_ip = SUBNET + "#{n+10}"
      compute.vm.box = "ksertonys/minijessie"
      compute.vm.box_version = "0.0.1"
      compute.vm.hostname = "cloud#{n+1}"
      compute.vm.network "private_network", ip: "#{vm_ip}"
      compute.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 1
      end
      #compute.vm.synced_folder "../", "/vagrant", disabled: false
      compute.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          mkdir /root/.ssh
          echo #{ssh_pub_key} > /root/.ssh/authorized_keys
        SHELL
      end
    end
  end
end
